### ISSUE TITLE
[NEOVIM] Some editor features

### ISSUE THREAD

**Issue by paulopatto** [paulopatto/dotfiles#16]
- [x] ~~Funcionalidade se [surrounding](https://www.lazyvim.org/plugins/coding#minisurround) mas com foco em poder selecionar um bloco (visual mode) e adiciona em volta `()`, `{}`, `""`, etc.~~ (WONTFIX)
- [x] ~~Função de auto close [pairs](https://www.lazyvim.org/plugins/coding#minipairs) para blocos~~ Já implementado com [nvim-autopairs](https://github.com/paulopatto/dotfiles/blob/feature/nvim-comments/nvim/lua/plugins/autopairs.lua) = #19 
- [x] Funcionalidade de [comentar linha](https://www.lazyvim.org/plugins/coding#nvim-ts-context-commentstring) ou blocos de código que nem o `CTRL+ /` di VSCode. -  #21 

Alguns plungins interessantes de entrar para o editor:

- [x] [Iluminate](https://github.com/RRethy/vim-illuminate): faz destaque em simbolos/palavras iguais no código.
- [x] [Todo Comments](https://github.com/folke/todo-comments.nvim): destaca palavras como TODO em comentários - #22
- [x] ~[Formatador](https://github.com/mhartington/formatter.nvim) Veja este [video](https://youtu.be/CVCBHHFXWNE?si=1LGDs3uFBUZu3FeY&t=727)~
